# Generated by Django 2.2.3 on 2023-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20230114_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
